"""add_hashed_password_to_users

Revision ID: 5d1fc09b65a7
Revises: 6ab9610af1eb
Create Date: 2026-09-07 20:33:39.603946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d1fc09b65a7'
down_revision: Union[str, Sequence[str], None] = '6ab9610af1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema safely with backfill for existing rows."""
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))

    from app.core.security import hash_password
    default_hash = hash_password("password123")
    op.execute(sa.text(f"UPDATE users SET hashed_password = '{default_hash}' WHERE hashed_password IS NULL;"))

    op.alter_column('users', 'hashed_password', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
